version: "3"
services:
    db:
        image: mysql
        env_file: .env
        security_opt:
            - seccomp:unconfined

    booking_service:
        build:
            context: ../
        depends_on:
            - db
        restart: on-failure
        env_file: .env

    proxy_server:
        image: nginx:1.17
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        depends_on:
            - booking_service


